baseURL = "https://orbitit.uk/"
languageCode = "en-us"
title = "Orbit IT - Cloud Native DevOps Consultancy"
theme = "hugo-arcana"
copyright = "© ORBIT IT 2022. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = true

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "About us"
            url = "/about-us/"
        [[params.footer.links.links]]
            title = "Careers"
            url = "/about-us/"

        [[params.footer.links]]
            header = "Technologies"
        [[params.footer.links.links]]
            title = "Google Cloud Platform"
            url = "https://cloud.google.com/"
        [[params.footer.links.links]]
            title = "Terraform"
            url = "https://www.terraform.io/"
        [[params.footer.links.links]]
            title = "Kubernetes"
            url = "https://kubernetes.io/"
        [[params.footer.links.links]]
            title = "Ansible"
            url = "https://www.ansible.com/"
        [[params.footer.links.links]]
            title = "Argo Workflows"
            url = "https://argoproj.github.io/argo-workflows/"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=hello@orbitit.uk"
